"""empty message

Revision ID: 1319ac6996ab
Revises: None
Create Date: 2015-03-15 14:21:27.465610

"""

# revision identifiers, used by Alembic.
revision = '1319ac6996ab'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
